pipeline {
    agent any
    stages {
        stage('Cloning Git') {
            steps {
                git 'https://github.com/alekha369/projCert.git'
            }
        }
        stage('Cloning Git') {
            steps {
               echo 'Slave configuration'
                   }
                }
              }
           }

/*...
- hosts: mywebservers
  gather_facts: False

  vars:
   - MyMessage: "Welcome to Ansible world!"

  pre_tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  tasks:
   - name: Nginx setup
     apt: pkg=nginx state=installed update_cache=true
   - name: index.html copy
     template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
*/

